[phases.setup]
nixPkgs = ["python39", "nodejs_20"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  "cd v3 && npm ci"
]

[phases.build]
cmds = [
  "cd v3 && npm run build"
]
